### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by sillyousu** [mgravell/Pipelines.Sockets.Unofficial#26]
I'm writing a .net core library on top of `Pipelines.Sockets.Unofficial`.

I found `Pipelines.Sockets.Unofficial.SocketConnection.DoSend` throw random exceptions ( ArgumentNullException/ArgumentOutOfRangeException etc) from 
https://github.com/dotnet/corefx/blob/7e484cac1442b0c3e1dcb1f42f43c4cd7d8ba4e5/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs#L177

The  `BufferList` was corrupted somehow.  It's seems like a race condition bug/heap corruption.
I have not track down the root cause nor have any theory yet.

```
19:09:47 Error DoSend excpetion 2 System.IO.IOException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Net.Sockets.SocketAsyncEventArgs.set_BufferList(IList`1 value)
   at Pipelines.Sockets.Unofficial.SocketConnection.DoSend(Socket socket, SocketAwaitableEventArgs args, ReadOnlySequence`1& buffer, String name) in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Send.cs:line 159
   at Pipelines.Sockets.Unofficial.SocketConnection.DoSendAsync() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Send.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.GetFlushAsyncResult()
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Kaka.Clusters.RemoteMessageAgent.DoSend(CancellationTokenSource cancellation, FrameProtocol protocol) in C:\Users\supei\source\dotnet\Kaka\src\Kaka\Clusters\RemoteMessageAgent.cs:line 288    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.GetFlushAsyncResult()
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Kaka.Clusters.RemoteMessageAgent.DoSend(CancellationTokenSource cancellation, FrameProtocol protocol) in C:\Users\supei\source\dotnet\Kaka\src\Kaka\Clusters\RemoteMessageAgent.cs:line 288
```

```
19:25:30 Error DoSend excpetion 2 System.IO.IOException: Value cannot be null.
Parameter name: segment ---> System.ArgumentNullException: Value cannot be null.
Parameter name: segment
   at System.Net.RangeValidationHelpers.ValidateSegment(ArraySegment`1 segment)
   at System.Net.Sockets.SocketAsyncEventArgs.set_BufferList(IList`1 value)
   at Pipelines.Sockets.Unofficial.SocketConnection.DoSend(Socket socket, SocketAwaitableEventArgs args, ReadOnlySequence`1& buffer, String name) in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Send.cs:line 159
   at Pipelines.Sockets.Unofficial.SocketConnection.DoSendAsync() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\SocketConnection.Send.cs:line 64
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.GetFlushAsyncResult()
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Kaka.Clusters.RemoteMessageAgent.DoSend(CancellationTokenSource cancellation, FrameProtocol protocol) in C:\Users\supei\source\dotnet\Kaka\src\Kaka\Clusters\RemoteMessageAgent.cs:line 288    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.GetFlushAsyncResult()
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Kaka.Clusters.RemoteMessageAgent.DoSend(CancellationTokenSource cancellation, FrameProtocol protocol) in C:\Users\supei\source\dotnet\Kaka\src\Kaka\Clusters\RemoteMessageAgent.cs:line 288
```

**Comment by mgravell** [comment]
I am very intrigued! Below is mostly my thought process while reading it. Sorry if it is disjointed - that's just how I think.

It *looks like* the problem here is with the actual list - I can't see any other way for `System.Collections.Generic.List`1.get_Item(Int32 index)` to throw, when it is accessed via:

``` c#
 int bufferCount = value.Count;
...
for (int i = 0; i < bufferCount; i++)
{
    ArraySegment<byte> buffer = value[i];
    RangeValidationHelpers.ValidateSegment(buffer);
    _bufferListInternal.Add(buffer);
}
```

so yes, I agree that the most likely problem here is somehow two threads squabbling over the same list. I'd also be happy to conclude that `buffer` coming out incomplete (a torn value) would be a possible cause of the second stack-trace, if we accept that the first stack-trace is caused by two threads fighting over the list.

So... how could such a thing have happened? (scratches beard)

I **suspect** that the problem is: in the "socket work completed synchronously case" we're recycling the buffer but *not* clearing the buffer list, but *not* clearing the buffer-list; that list is then up for grabs, and if the next IO work is also multi-buffer, we'll get into problems. Yeah, I'm pretty confident that's what has happened... fixing.

**Comment by mgravell** [comment]
https://www.nuget.org/packages/Pipelines.Sockets.Unofficial/2.0.5 uploaded to nuget - please let me know how you get on, and thanks for a great error report

**Comment by sillyousu** [comment]
I will test it tomorrow. thank you！

**Comment by sillyousu** [comment]
I see the same error in `v2.0.7`.

**Comment by mgravell** [comment]
Awesome, great to hear - and great to fix this bug; I hadn't seen it, but: quite likely it was causing some connection failures that I wasn't attributing to this, especially under load
