### ISSUE TITLE
Test: ConnectTests.Connect - Fails on my machine

### ISSUE THREAD

**Issue by TimLovellSmith** [mgravell/Pipelines.Sockets.Unofficial#55]
(Running on Windows)
```
[xUnit.net 00:00:14.88]     Pipelines.Sockets.Unofficial.Tests.ConnectTests.Connect [FAIL]
  X Pipelines.Sockets.Unofficial.Tests.ConnectTests.Connect [5s 77ms]
  Error Message:
   System.TimeoutException : The operation has timed out.
  Stack Trace:
     at Pipelines.Sockets.Unofficial.Internal.Throw.Timeout(String message) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 33
   at Pipelines.Sockets.Unofficial.Tests.ConnectTests.<Connect>d__8.MoveNext() in /_/tests/Pipelines.Sockets.Unofficial.Tests/ConnectTests.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by TimLovellSmith** [comment]
I tried increasing the 5000ms timeout in case my machine is just too slow. And that seems to have fixed it. ;-(
(CPU utilization is also pretty high in general while I'm running tests).
